# Generated by Django 2.0.2 on 2018-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='huerfanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Raza', models.CharField(max_length=200, verbose_name='Raza')),
                ('Descripcion', models.TextField(verbose_name='Descripcion')),
                ('Fotografia', models.ImageField(upload_to='adopcion')),
                ('Estado', models.CharField(choices=[('RES', 'Rescatado'), ('DIS', 'Disponible'), ('ADO', 'Adoptado')], max_length=200, verbose_name='Estado')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('Update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('Run', models.CharField(max_length=200, verbose_name='Run')),
                ('FecNac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('Email', models.CharField(max_length=200, verbose_name='Correo Electronio')),
                ('Region', models.CharField(max_length=200, verbose_name='Region')),
                ('Comuna', models.CharField(max_length=200, verbose_name='comuna')),
                ('TipoVivienda', models.CharField(max_length=200, verbose_name='tipo de vivienda')),
            ],
        ),
    ]
