# Generated by Django 2.0.2 on 2018-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='huerfanos',
            new_name='huerfano',
        ),
    ]
